CREATE TABLE [dbo].[SiteVisit]
(
	EventId UNIQUEIDENTIFIER NOT NULL,
	IsDataEntryComplete BIT NOT NULL CONSTRAINT DF_SiteVisit__IsDataEntryComplete DEFAULT(0),
	LocationId UNIQUEIDENTIFIER NOT NULL,
	StartTime DATETIME NOT NULL,
	EndTime DATETIME NOT NULL,
	StartConditionId UNIQUEIDENTIFIER NOT NULL,
	EndConditionId UNIQUEIDENTIFIER NULL,
	ObserverId UNIQUEIDENTIFIER NULL,
	RecorderId UNIQUEIDENTIFIER NULL,
	Comments VARCHAR(1000) NULL,
	StartYear as YEAR(StartTime),
	CONSTRAINT PK_SiteVisit PRIMARY KEY CLUSTERED (EventId)
)