//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web.UI.WebControls;

public partial class Review {
    
    /// <summary>
    /// SurveySteps1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected SurveySteps SurveySteps1;
    
    /// <summary>
    /// SiteVisitPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel SiteVisitPanel;
    
    /// <summary>
    /// SiteVisitedLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitedLabel;
    
    /// <summary>
    /// SiteVisited control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisited;
    
    /// <summary>
    /// SiteVisitObserverLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitObserverLabel;
    
    /// <summary>
    /// SiteVisitObserver control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitObserver;
    
    /// <summary>
    /// SiteVisitRecorderLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitRecorderLabel;
    
    /// <summary>
    /// SiteVisitRecorder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitRecorder;
    
    /// <summary>
    /// StartConditionsPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel StartConditionsPanel;
    
    /// <summary>
    /// StartTimeLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTimeLabel;
    
    /// <summary>
    /// StartTime control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTime;
    
    /// <summary>
    /// StartSkyLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartSkyLabel;
    
    /// <summary>
    /// StartSky control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartSky;
    
    /// <summary>
    /// StartWindLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartWindLabel;
    
    /// <summary>
    /// StartWind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartWind;
    
    /// <summary>
    /// StartTempLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTempLabel;
    
    /// <summary>
    /// StartTemperature control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTemperature;
    
    /// <summary>
    /// EndConditionsPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel EndConditionsPanel;
    
    /// <summary>
    /// EndTimeLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTimeLabel;
    
    /// <summary>
    /// EndTime control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTime;
    
    /// <summary>
    /// EndSkyLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndSkyLabel;
    
    /// <summary>
    /// EndSky control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndSky;
    
    /// <summary>
    /// EndWindLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndWindLabel;
    
    /// <summary>
    /// EndWind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndWind;
    
    /// <summary>
    /// EndTempLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTempLabel;
    
    /// <summary>
    /// EndTemperature control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTemperature;
    
    /// <summary>
    /// PointSurveyPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel PointSurveyPanel;
    
    /// <summary>
    /// PointSurveyList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ListView PointSurveyList;
    
    /// <summary>
    /// PointSurveyObservationPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel PointSurveyObservationPanel;
    
    /// <summary>
    /// PointSurveyObservationList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ListView PointSurveyObservationList;
    
    /// <summary>
    /// SupplementalsPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel SupplementalsPanel;
    
    /// <summary>
    /// SupplementalList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ListView SupplementalList;
    
    /// <summary>
    /// SubmitReview control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Button SubmitReview;
    
    /// <summary>
    /// SupplementalObservationDataSource control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ObjectDataSource SupplementalObservationDataSource;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new IbaMasterPage Master {
        get {
            return ((IbaMasterPage)(base.Master));
        }
    }
}
