//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using AjaxControlToolkit;
using System.Web.UI.WebControls;

public partial class SiteConditionsPage {
    
    /// <summary>
    /// StartNewSession control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LinkButton StartNewSession;
    
    /// <summary>
    /// ValidationSummary1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ValidationSummary ValidationSummary1;
    
    /// <summary>
    /// SiteVisitPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel SiteVisitPanel;
    
    /// <summary>
    /// SiteVisitSiteLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitSiteLabel;
    
    /// <summary>
    /// SiteVisited control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList SiteVisited;
    
    /// <summary>
    /// SiteVisitDateLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitDateLabel;
    
    /// <summary>
    /// SiteVisitDateRequired control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RequiredFieldValidator SiteVisitDateRequired;
    
    /// <summary>
    /// VisitDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox VisitDate;
    
    /// <summary>
    /// SiteVisitDateCalExt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CalendarExtender SiteVisitDateCalExt;
    
    /// <summary>
    /// SiteVisitDateValidator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CompareValidator SiteVisitDateValidator;
    
    /// <summary>
    /// RetrieveIncomplete control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LinkButton RetrieveIncomplete;
    
    /// <summary>
    /// SiteVisitObserverLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitObserverLabel;
    
    /// <summary>
    /// SiteVisitObserver control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList SiteVisitObserver;
    
    /// <summary>
    /// SiteVisitRecorderLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label SiteVisitRecorderLabel;
    
    /// <summary>
    /// SiteVisitRecorder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList SiteVisitRecorder;
    
    /// <summary>
    /// StartConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel StartConditions;
    
    /// <summary>
    /// StartTimeLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTimeLabel;
    
    /// <summary>
    /// StartTimeRequired control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RequiredFieldValidator StartTimeRequired;
    
    /// <summary>
    /// StartTime control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox StartTime;
    
    /// <summary>
    /// StartTimeValidator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CustomValidator StartTimeValidator;
    
    /// <summary>
    /// StartSkyLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartSkyLabel;
    
    /// <summary>
    /// StartSky control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList StartSky;
    
    /// <summary>
    /// StartWindLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartWindLabel;
    
    /// <summary>
    /// StartWind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList StartWind;
    
    /// <summary>
    /// StartTempLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label StartTempLabel;
    
    /// <summary>
    /// StartTemperatureRequired control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RequiredFieldValidator StartTemperatureRequired;
    
    /// <summary>
    /// StartTemperature control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox StartTemperature;
    
    /// <summary>
    /// StartTemp_Radio control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RadioButtonList StartTemp_Radio;
    
    /// <summary>
    /// StartTemperatureValidator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CustomValidator StartTemperatureValidator;
    
    /// <summary>
    /// EndConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel EndConditions;
    
    /// <summary>
    /// EndTimeLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTimeLabel;
    
    /// <summary>
    /// EndTimeRequired control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RequiredFieldValidator EndTimeRequired;
    
    /// <summary>
    /// EndTime control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox EndTime;
    
    /// <summary>
    /// EndTimeValidator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CustomValidator EndTimeValidator;
    
    /// <summary>
    /// EndSkyLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndSkyLabel;
    
    /// <summary>
    /// EndSky control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList EndSky;
    
    /// <summary>
    /// EndWindLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndWindLabel;
    
    /// <summary>
    /// EndWind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList EndWind;
    
    /// <summary>
    /// EndTempLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label EndTempLabel;
    
    /// <summary>
    /// EndTemperatureRequired control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RequiredFieldValidator EndTemperatureRequired;
    
    /// <summary>
    /// EndTemperature control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox EndTemperature;
    
    /// <summary>
    /// EndTemp_Radio control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected RadioButtonList EndTemp_Radio;
    
    /// <summary>
    /// EndTemperatureValidator control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CustomValidator EndTemperatureValidator;
    
    /// <summary>
    /// SubmitSiteConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ImageButton SubmitSiteConditions;
    
    /// <summary>
    /// SkyCodeDataSource control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ObjectDataSource SkyCodeDataSource;
    
    /// <summary>
    /// WindCodeDataSource control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ObjectDataSource WindCodeDataSource;
    
    /// <summary>
    /// SiteVisitStepsControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected SurveySteps SiteVisitStepsControl1;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new IbaMasterPage Master {
        get {
            return ((IbaMasterPage)(base.Master));
        }
    }
}
