




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `local`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=(localdb)\ProjectsV12;Integrated Security=SSPI;Database=IbaMonitoring.SQL`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using NServiceKit.OrmLite;
using NServiceKit.DataAnnotations;
using NServiceKit.DesignPatterns.Model;
using System.ComponentModel.DataAnnotations;

namespace IbaMonitoring.ServiceTests.Orm
{
	[Alias("IbaProgram")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class IbaProgram : IHasId<Guid> 
    {
        [Alias("IbaProgramId")]
        [Required]
        public Guid Id { get; set;}
        public string ProgramDescription { get; set;}
    }
	[Alias("Location")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Location : IHasId<Guid> 
    {
        [Alias("LocationId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string LocationName { get; set;}
        public decimal? Latitude { get; set;}
        public decimal? Longitude { get; set;}
        [Required]
        public Guid LocationTypeId { get; set;}
        public Guid? ParentLocationId { get; set;}
        public string CodeName { get; set;}
    }
	[Alias("Lookup")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Lookup : IHasId<Guid> 
    {
        [Alias("LookupId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string Value { get; set;}
        public Guid? ParentLookupId { get; set;}
    }
	[Alias("Observation")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Observation : IHasId<long> 
    {
        [Alias("ObservationId")]
        [AutoIncrement]
        public long Id { get; set;}
        [Required]
        public Guid EventId { get; set;}
        [Required]
        public Guid SpeciesId { get; set;}
        public string Comments { get; set;}
        [Required]
        public Guid ObservationTypeId { get; set;}
    }
	[Alias("Person")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Person : IHasId<Guid> 
    {
        [Alias("PersonId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string FirstName { get; set;}
        [Required]
        public string LastName { get; set;}
        public string OpenId { get; set;}
        public string EmailAddress { get; set;}
        public string PhoneNumber { get; set;}
        [Required]
        public short PersonStatus { get; set;}
        [Required]
        public short PersonRole { get; set;}
        [Required]
        public bool HasBeenTrained { get; set;}
        [Required]
        public bool HasClipboard { get; set;}
        public string Address1 { get; set;}
        public string Address2 { get; set;}
        public string City { get; set;}
        public string State { get; set;}
        public string ZipCode { get; set;}
        public string Country { get; set;}
    }
	[Alias("PointSurvey")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class PointSurvey : IHasId<Guid> 
    {
        [Alias("EventId")]
        [Required]
        public Guid Id { get; set;}
        public Guid? SiteVisitId { get; set;}
        [Required]
        public Guid LocationId { get; set;}
        [Required]
        public DateTime StartTime { get; set;}
        [Required]
        public DateTime EndTime { get; set;}
        public byte? NoiseCode { get; set;}
    }
	[Alias("Season")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Season : IHasId<Guid> 
    {
        [Alias("SeasonId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string SeasonDescription { get; set;}
        [Required]
        public Guid IbaProgramId { get; set;}
        public DateTime? StartWeek { get; set;}
        public DateTime? EndWeek { get; set;}
    }
	[Alias("SiteBoundary")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class SiteBoundary : IHasId<int> 
    {
        [Alias("SiteBoundaryId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public Guid SiteId { get; set;}
        [Required]
        public decimal Latitude { get; set;}
        [Required]
        public decimal Longitude { get; set;}
        [Required]
        public int VertexSequence { get; set;}
    }
	[Alias("SiteCondition")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class SiteCondition : IHasId<Guid> 
    {
        [Alias("ConditionId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public int Temperature { get; set;}
        [Required]
        public string Scale { get; set;}
        [Required]
        public byte Wind { get; set;}
        [Required]
        public byte Sky { get; set;}
        [Required]
        public Guid SiteVisitId { get; set;}
    }
	[Alias("SiteVisit")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class SiteVisit : IHasId<Guid> 
    {
        [Alias("EventId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public bool IsDataEntryComplete { get; set;}
        [Required]
        public Guid LocationId { get; set;}
        [Required]
        public DateTime StartTime { get; set;}
        [Required]
        public DateTime EndTime { get; set;}
        [Required]
        public Guid StartConditionId { get; set;}
        public Guid? EndConditionId { get; set;}
        public Guid? ObserverId { get; set;}
        public Guid? RecorderId { get; set;}
        public string Comments { get; set;}
        [Compute]        
        public int? StartYear { get; set;}
    }
	[Alias("Species")]
	[Schema("dbo")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Species : IHasId<Guid> 
    {
        [Alias("SpeciesId")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public string AlphaCode { get; set;}
        public string CommonName { get; set;}
        public string ScientificName { get; set;}
        [Required]
        public int WarningCount { get; set;}
        [Required]
        public bool UseForCommunityMeasures { get; set;}
        public string MigrationGuild { get; set;}
        public string ConservationGuild { get; set;}
    }
}
#pragma warning restore 1591


