//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

public partial class Account {
    
    /// <summary>
    /// UserProfilesPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Panel UserProfilesPanel;
    
    /// <summary>
    /// ShowInactive control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected LinkButton ShowInactive;
    
    /// <summary>
    /// ExcludeInactive control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected HiddenField ExcludeInactive;
    
    /// <summary>
    /// lvUsers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected ListView lvUsers;
    
    /// <summary>
    /// ItemDataPager control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DataPager ItemDataPager;
    
    /// <summary>
    /// EditProfile control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected HtmlGenericControl EditProfile;
    
    /// <summary>
    /// NonAdminLevelAccessProfile1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected account_NonAdminLevelAccessProfile NonAdminLevelAccessProfile1;
    
    /// <summary>
    /// OnlyAdminLevelAccessProfile1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected account_OnlyAdminLevelAccessProfile OnlyAdminLevelAccessProfile1;
    
    /// <summary>
    /// btnSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Button btnSave;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new IbaMasterPage Master {
        get {
            return ((IbaMasterPage)(base.Master));
        }
    }
}
