//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web.UI.WebControls;

public partial class account_OnlyAdminLevelAccessProfile {
    
    /// <summary>
    /// lblUserID control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label lblUserID;
    
    /// <summary>
    /// tbxUserID control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox tbxUserID;
    
    /// <summary>
    /// HasBeenTrainedLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label HasBeenTrainedLabel;
    
    /// <summary>
    /// cbHasBeenTrained control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CheckBox cbHasBeenTrained;
    
    /// <summary>
    /// lblGpsSerialNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label lblGpsSerialNumber;
    
    /// <summary>
    /// tbxGpsSerialNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected TextBox tbxGpsSerialNumber;
    
    /// <summary>
    /// HasClipboardLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label HasClipboardLabel;
    
    /// <summary>
    /// cbHasClipboard control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected CheckBox cbHasClipboard;
    
    /// <summary>
    /// RoleLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label RoleLabel;
    
    /// <summary>
    /// ddlRoles control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList ddlRoles;
    
    /// <summary>
    /// lblStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected Label lblStatus;
    
    /// <summary>
    /// ddlStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected DropDownList ddlStatus;
}
